// <auto-generated />
using System;
using CommonSpaceWebsite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CommonSpaceWebsite.Migrations
{
    [DbContext(typeof(CommonSpaceDbContext))]
    [Migration("20250505200544_123123123123")]
    partial class _123123123123
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CommonSpaceWebsite.Models.CleaningTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CleaningTasks");
                });

            modelBuilder.Entity("CommonSpaceWebsite.Models.CleaningWeek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CleanerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CleanerId");

                    b.ToTable("CleaningWeeks");
                });

            modelBuilder.Entity("CommonSpaceWebsite.Models.CleaningWeekTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<int>("WeekId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.HasIndex("WeekId");

                    b.ToTable("CleaningWeekTasks");
                });

            modelBuilder.Entity("CommonSpaceWebsite.Models.ShoppingItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("IsPurchased")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PurchasedById")
                        .HasColumnType("int");

                    b.Property<int?>("WeekId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PurchasedById");

                    b.HasIndex("WeekId");

                    b.ToTable("ShoppingItems");
                });

            modelBuilder.Entity("CommonSpaceWebsite.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CommonSpaceWebsite.Models.CleaningWeek", b =>
                {
                    b.HasOne("CommonSpaceWebsite.Models.User", "Cleaner")
                        .WithMany("AssignedWeeks")
                        .HasForeignKey("CleanerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cleaner");
                });

            modelBuilder.Entity("CommonSpaceWebsite.Models.CleaningWeekTask", b =>
                {
                    b.HasOne("CommonSpaceWebsite.Models.CleaningTask", "Task")
                        .WithMany("WeekTasks")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CommonSpaceWebsite.Models.CleaningWeek", "Week")
                        .WithMany("Tasks")
                        .HasForeignKey("WeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("Week");
                });

            modelBuilder.Entity("CommonSpaceWebsite.Models.ShoppingItem", b =>
                {
                    b.HasOne("CommonSpaceWebsite.Models.User", "PurchasedBy")
                        .WithMany("PurchasedItems")
                        .HasForeignKey("PurchasedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CommonSpaceWebsite.Models.CleaningWeek", "Week")
                        .WithMany("ShoppingList")
                        .HasForeignKey("WeekId");

                    b.Navigation("PurchasedBy");

                    b.Navigation("Week");
                });

            modelBuilder.Entity("CommonSpaceWebsite.Models.CleaningTask", b =>
                {
                    b.Navigation("WeekTasks");
                });

            modelBuilder.Entity("CommonSpaceWebsite.Models.CleaningWeek", b =>
                {
                    b.Navigation("ShoppingList");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("CommonSpaceWebsite.Models.User", b =>
                {
                    b.Navigation("AssignedWeeks");

                    b.Navigation("PurchasedItems");
                });
#pragma warning restore 612, 618
        }
    }
}
